/** Liquid US-listed stock universe (~100) for bubbles + top-by-mkt-cap tables — no keys. */
export const STOCK_UNIVERSE: { yahoo: string; label: string; name: string }[] = [
  { yahoo: 'NVDA', label: 'NVDA', name: 'NVIDIA' },
  { yahoo: 'MSFT', label: 'MSFT', name: 'Microsoft' },
  { yahoo: 'AAPL', label: 'AAPL', name: 'Apple' },
  { yahoo: 'GOOGL', label: 'GOOGL', name: 'Alphabet' },
  { yahoo: 'AMZN', label: 'AMZN', name: 'Amazon' },
  { yahoo: 'META', label: 'META', name: 'Meta' },
  { yahoo: 'AVGO', label: 'AVGO', name: 'Broadcom' },
  { yahoo: 'TSLA', label: 'TSLA', name: 'Tesla' },
  { yahoo: 'F', label: 'F', name: 'Ford' },
  { yahoo: 'BRK-B', label: 'BRK-B', name: 'Berkshire' },
  { yahoo: 'JPM', label: 'JPM', name: 'JPMorgan' },
  { yahoo: 'WMT', label: 'WMT', name: 'Walmart' },
  { yahoo: 'LLY', label: 'LLY', name: 'Eli Lilly' },
  { yahoo: 'V', label: 'V', name: 'Visa' },
  { yahoo: 'XOM', label: 'XOM', name: 'Exxon' },
  { yahoo: 'MA', label: 'MA', name: 'Mastercard' },
  { yahoo: 'ORCL', label: 'ORCL', name: 'Oracle' },
  { yahoo: 'UNH', label: 'UNH', name: 'UnitedHealth' },
  { yahoo: 'COST', label: 'COST', name: 'Costco' },
  { yahoo: 'NFLX', label: 'NFLX', name: 'Netflix' },
  { yahoo: 'PG', label: 'PG', name: 'P&G' },
  { yahoo: 'JNJ', label: 'JNJ', name: 'Johnson & Johnson' },
  { yahoo: 'HD', label: 'HD', name: 'Home Depot' },
  { yahoo: 'ABBV', label: 'ABBV', name: 'AbbVie' },
  { yahoo: 'BAC', label: 'BAC', name: 'Bank of America' },
  { yahoo: 'CRM', label: 'CRM', name: 'Salesforce' },
  { yahoo: 'KO', label: 'KO', name: 'Coca-Cola' },
  { yahoo: 'MRK', label: 'MRK', name: 'Merck' },
  { yahoo: 'CVX', label: 'CVX', name: 'Chevron' },
  { yahoo: 'AMD', label: 'AMD', name: 'AMD' },
  { yahoo: 'PEP', label: 'PEP', name: 'PepsiCo' },
  { yahoo: 'TMO', label: 'TMO', name: 'Thermo Fisher' },
  { yahoo: 'CSCO', label: 'CSCO', name: 'Cisco' },
  { yahoo: 'LIN', label: 'LIN', name: 'Linde' },
  { yahoo: 'ADBE', label: 'ADBE', name: 'Adobe' },
  { yahoo: 'WFC', label: 'WFC', name: 'Wells Fargo' },
  { yahoo: 'MCD', label: 'MCD', name: 'McDonald\'s' },
  { yahoo: 'ABT', label: 'ABT', name: 'Abbott' },
  { yahoo: 'ACN', label: 'ACN', name: 'Accenture' },
  { yahoo: 'TXN', label: 'TXN', name: 'Texas Instruments' },
  { yahoo: 'IBM', label: 'IBM', name: 'IBM' },
  { yahoo: 'QCOM', label: 'QCOM', name: 'Qualcomm' },
  { yahoo: 'CAT', label: 'CAT', name: 'Caterpillar' },
  { yahoo: 'GE', label: 'GE', name: 'GE' },
  { yahoo: 'PM', label: 'PM', name: 'Philip Morris' },
  { yahoo: 'INTU', label: 'INTU', name: 'Intuit' },
  { yahoo: 'VZ', label: 'VZ', name: 'Verizon' },
  { yahoo: 'AMAT', label: 'AMAT', name: 'Applied Materials' },
  { yahoo: 'ISRG', label: 'ISRG', name: 'Intuitive Surgical' },
  { yahoo: 'NOW', label: 'NOW', name: 'ServiceNow' },
  { yahoo: 'DIS', label: 'DIS', name: 'Disney' },
  { yahoo: 'UBER', label: 'UBER', name: 'Uber' },
  { yahoo: 'GS', label: 'GS', name: 'Goldman Sachs' },
  { yahoo: 'BKNG', label: 'BKNG', name: 'Booking' },
  { yahoo: 'SPGI', label: 'SPGI', name: 'S&P Global' },
  { yahoo: 'AXP', label: 'AXP', name: 'American Express' },
  { yahoo: 'MS', label: 'MS', name: 'Morgan Stanley' },
  { yahoo: 'PFE', label: 'PFE', name: 'Pfizer' },
  { yahoo: 'T', label: 'T', name: 'AT&T' },
  { yahoo: 'NEE', label: 'NEE', name: 'NextEra Energy' },
  { yahoo: 'RTX', label: 'RTX', name: 'RTX' },
  { yahoo: 'LOW', label: 'LOW', name: 'Lowe\'s' },
  { yahoo: 'BLK', label: 'BLK', name: 'BlackRock' },
  { yahoo: 'HON', label: 'HON', name: 'Honeywell' },
  { yahoo: 'UNP', label: 'UNP', name: 'Union Pacific' },
  { yahoo: 'SYK', label: 'SYK', name: 'Stryker' },
  { yahoo: 'TJX', label: 'TJX', name: 'TJX' },
  { yahoo: 'PLD', label: 'PLD', name: 'Prologis' },
  { yahoo: 'BA', label: 'BA', name: 'Boeing' },
  { yahoo: 'SCHW', label: 'SCHW', name: 'Schwab' },
  { yahoo: 'BMY', label: 'BMY', name: 'Bristol Myers' },
  { yahoo: 'C', label: 'C', name: 'Citigroup' },
  { yahoo: 'MDT', label: 'MDT', name: 'Medtronic' },
  { yahoo: 'GILD', label: 'GILD', name: 'Gilead' },
  { yahoo: 'ADP', label: 'ADP', name: 'ADP' },
  { yahoo: 'VRTX', label: 'VRTX', name: 'Vertex' },
  { yahoo: 'PANW', label: 'PANW', name: 'Palo Alto' },
  { yahoo: 'SBUX', label: 'SBUX', name: 'Starbucks' },
  { yahoo: 'DE', label: 'DE', name: 'Deere' },
  { yahoo: 'LRCX', label: 'LRCX', name: 'Lam Research' },
  { yahoo: 'ADI', label: 'ADI', name: 'Analog Devices' },
  { yahoo: 'MU', label: 'MU', name: 'Micron' },
  { yahoo: 'INTC', label: 'INTC', name: 'Intel' },
  { yahoo: 'CMCSA', label: 'CMCSA', name: 'Comcast' },
  { yahoo: 'REGN', label: 'REGN', name: 'Regeneron' },
  { yahoo: 'AMT', label: 'AMT', name: 'American Tower' },
  { yahoo: 'CB', label: 'CB', name: 'Chubb' },
  { yahoo: 'ETN', label: 'ETN', name: 'Eaton' },
  { yahoo: 'MMC', label: 'MMC', name: 'Marsh McLennan' },
  { yahoo: 'SO', label: 'SO', name: 'Southern Co' },
  { yahoo: 'PLTR', label: 'PLTR', name: 'Palantir' },
  { yahoo: 'CRWD', label: 'CRWD', name: 'CrowdStrike' },
  { yahoo: 'SHOP', label: 'SHOP', name: 'Shopify' },
  { yahoo: 'XYZ', label: 'XYZ', name: 'Block' },
  { yahoo: 'COIN', label: 'COIN', name: 'Coinbase' },
  { yahoo: 'MSTR', label: 'MSTR', name: 'MicroStrategy' },
  { yahoo: 'TSM', label: 'TSM', name: 'TSMC' },
  { yahoo: 'NVO', label: 'NVO', name: 'Novo Nordisk' },
  { yahoo: 'ASML', label: 'ASML', name: 'ASML' },
  { yahoo: 'SAP', label: 'SAP', name: 'SAP' },
  { yahoo: 'AZN', label: 'AZN', name: 'AstraZeneca' },
  { yahoo: 'TM', label: 'TM', name: 'Toyota' },
  { yahoo: 'BABA', label: 'BABA', name: 'Alibaba' },
  { yahoo: 'HSBC', label: 'HSBC', name: 'HSBC' },
];

/** Liquid ETF universe (~50) for bubbles + top-by-AUM/mkt-cap tables. */
export const ETF_UNIVERSE: { yahoo: string; label: string; name: string }[] = [
  { yahoo: 'SPY', label: 'SPY', name: 'SPDR S&P 500' },
  { yahoo: 'QQQ', label: 'QQQ', name: 'Invesco QQQ' },
  { yahoo: 'IWM', label: 'IWM', name: 'iShares Russell 2000' },
  { yahoo: 'DIA', label: 'DIA', name: 'SPDR Dow Jones' },
  { yahoo: 'SMH', label: 'SMH', name: 'VanEck Semiconductor' },
  { yahoo: 'USD', label: 'USD', name: 'ProShares Ultra Semiconductors' },
  { yahoo: 'XLF', label: 'XLF', name: 'Financial Select' },
  { yahoo: 'XLE', label: 'XLE', name: 'Energy Select' },
  { yahoo: 'XLK', label: 'XLK', name: 'Technology Select' },
  { yahoo: 'XLV', label: 'XLV', name: 'Health Care Select' },
  { yahoo: 'XLI', label: 'XLI', name: 'Industrial Select' },
  { yahoo: 'XLY', label: 'XLY', name: 'Consumer Disc.' },
  { yahoo: 'XLP', label: 'XLP', name: 'Consumer Staples' },
  { yahoo: 'XLU', label: 'XLU', name: 'Utilities Select' },
  { yahoo: 'XLB', label: 'XLB', name: 'Materials Select' },
  { yahoo: 'XLRE', label: 'XLRE', name: 'Real Estate Select' },
  { yahoo: 'XLC', label: 'XLC', name: 'Communication Svcs' },
  { yahoo: 'GLD', label: 'GLD', name: 'SPDR Gold' },
  { yahoo: 'GLTR', label: 'GLTR', name: 'Precious Metals Basket' },
  { yahoo: 'SLV', label: 'SLV', name: 'iShares Silver' },
  { yahoo: 'USO', label: 'USO', name: 'United States Oil' },
  { yahoo: 'CPER', label: 'CPER', name: 'US Copper Index' },
  { yahoo: 'COPX', label: 'COPX', name: 'Global X Copper Miners' },
  { yahoo: 'TLT', label: 'TLT', name: 'iShares 20+ Year Treasury' },
  { yahoo: 'IEF', label: 'IEF', name: 'iShares 7-10 Year Treasury' },
  { yahoo: 'HYG', label: 'HYG', name: 'iShares High Yield Corp' },
  { yahoo: 'LQD', label: 'LQD', name: 'iShares Inv Grade Corp' },
  { yahoo: 'EFA', label: 'EFA', name: 'iShares MSCI EAFE' },
  { yahoo: 'EEM', label: 'EEM', name: 'iShares MSCI Emerging' },
  { yahoo: 'VTI', label: 'VTI', name: 'Vanguard Total Stock' },
  { yahoo: 'VOO', label: 'VOO', name: 'Vanguard S&P 500' },
  { yahoo: 'VEA', label: 'VEA', name: 'Vanguard FTSE Developed' },
  { yahoo: 'VWO', label: 'VWO', name: 'Vanguard FTSE Emerging' },
  { yahoo: 'ARKK', label: 'ARKK', name: 'ARK Innovation' },
  { yahoo: 'SOXX', label: 'SOXX', name: 'iShares Semiconductor' },
  { yahoo: 'IGV', label: 'IGV', name: 'iShares Expanded Tech-Software' },
  { yahoo: 'XBI', label: 'XBI', name: 'SPDR S&P Biotech' },
  { yahoo: 'KWEB', label: 'KWEB', name: 'KraneShares CSI China Internet' },
  { yahoo: 'BITO', label: 'BITO', name: 'ProShares Bitcoin Strategy' },
  { yahoo: 'IYR', label: 'IYR', name: 'iShares US Real Estate' },
  { yahoo: 'VNQ', label: 'VNQ', name: 'Vanguard Real Estate' },
  { yahoo: 'AGG', label: 'AGG', name: 'iShares Core US Aggregate Bond' },
  { yahoo: 'BND', label: 'BND', name: 'Vanguard Total Bond' },
  { yahoo: 'TIP', label: 'TIP', name: 'iShares TIPS Bond' },
  { yahoo: 'UNG', label: 'UNG', name: 'United States Natural Gas' },
  { yahoo: 'DBA', label: 'DBA', name: 'Invesco DB Agriculture' },
  { yahoo: 'GDX', label: 'GDX', name: 'VanEck Gold Miners' },
  { yahoo: 'TAN', label: 'TAN', name: 'Invesco Solar' },
  { yahoo: 'ICLN', label: 'ICLN', name: 'iShares Global Clean Energy' },
  { yahoo: 'IVV', label: 'IVV', name: 'iShares Core S&P 500' },
  { yahoo: 'IEFA', label: 'IEFA', name: 'iShares Core MSCI EAFE' },
];

export type Timeframe = '1h' | '4h' | '8h' | '12h' | '24h' | '7d' | '30d' | '1y';
export type BubbleCategory = 'cryptos' | 'solana' | 'stocks' | 'etfs';

/** Lookback hours for chart-based % (used for equities). */
export const TF_HOURS: Record<Timeframe, number> = {
  '1h': 1,
  '4h': 4,
  '8h': 8,
  '12h': 12,
  '24h': 24,
  '7d': 24 * 7,
  '30d': 24 * 30,
  '1y': 24 * 365,
};

export const CRYPTO_TFS: Timeframe[] = ['1h', '24h', '7d', '30d', '1y'];
export const EQUITY_TFS: Timeframe[] = ['1h', '4h', '8h', '12h', '24h', '7d', '30d', '1y'];
